language: python
cache: pip
env:
  - C7N_TEST_WORKERS=8

matrix:
    include:
        - python: 2.7
        - python: 3.6
        - python: 3.7
          dist: xenial
          sudo: true

install:
  - pip install tox
script:
  - TOXENV=`tools/dev/citoxenv.py` tox
