{{- if .Values.defaultSecretEnvironment -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-default-secret-environment"
data:
{{- range $secretName, $secretValue := .Values.defaultSecretEnvironment }}
  {{ $secretName }}: {{ $secretValue }}
{{- end -}}
{{- end }}
