{{- range $host := .Values.subscriptionHosts }}
{{ if $host.secretEnvironment -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $host.name }}-secret-environment"
data:
{{- range $secretName, $secretValue := $host.secretEnvironment }}
  {{ $secretName }}: {{ $secretValue }}
{{- end -}}
{{- end -}}
{{- end }}